// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Checkout.Com.BasketPrototype.ClientLib.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BasketItemCreateModel
    {
        /// <summary>
        /// Initializes a new instance of the BasketItemCreateModel class.
        /// </summary>
        public BasketItemCreateModel() { }

        /// <summary>
        /// Initializes a new instance of the BasketItemCreateModel class.
        /// </summary>
        public BasketItemCreateModel(string productSku, int count)
        {
            ProductSku = productSku;
            Count = count;
        }

        /// <summary>
        /// Gets or sets the product sku.
        /// </summary>
        [JsonProperty(PropertyName = "ProductSku")]
        public string ProductSku { get; set; }

        /// <summary>
        /// Gets or sets the count.
        /// </summary>
        [JsonProperty(PropertyName = "Count")]
        public int Count { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ProductSku == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ProductSku");
            }
            if (this.Count > 1000)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Count", 1000);
            }
            if (this.Count < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Count", 1);
            }
        }
    }
}
