// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Checkout.Com.BasketPrototype.ClientLib
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for BasketItem.
    /// </summary>
    public static partial class BasketItemExtensions
    {
            /// <summary>
            /// Creates a new basket item.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='basketGuid'>
            /// The basket unique identifier.
            /// </param>
            /// <param name='basketItemCreateModel'>
            /// The basket item create model.
            /// </param>
            /// <param name='userGuid'>
            /// </param>
            public static Guid? PostBasketItemAsync(this IBasketItem operations, Guid basketGuid, BasketItemCreateModel basketItemCreateModel, string userGuid)
            {
                return Task.Factory.StartNew(s => ((IBasketItem)s).PostBasketItemAsyncAsync(basketGuid, basketItemCreateModel, userGuid), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates a new basket item.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='basketGuid'>
            /// The basket unique identifier.
            /// </param>
            /// <param name='basketItemCreateModel'>
            /// The basket item create model.
            /// </param>
            /// <param name='userGuid'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Guid?> PostBasketItemAsyncAsync(this IBasketItem operations, Guid basketGuid, BasketItemCreateModel basketItemCreateModel, string userGuid, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostBasketItemAsyncWithHttpMessagesAsync(basketGuid, basketItemCreateModel, userGuid, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Changes the content of basket item.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='basketitemGuid'>
            /// The basketitem unique identifier.
            /// </param>
            /// <param name='basketItemChangeModel'>
            /// The basket item change model.
            /// </param>
            /// <param name='userGuid'>
            /// </param>
            /// <param name='basketGuid'>
            /// </param>
            public static void PutBasketItemAsync(this IBasketItem operations, Guid basketitemGuid, BasketItemChangeModel basketItemChangeModel, string userGuid, string basketGuid)
            {
                Task.Factory.StartNew(s => ((IBasketItem)s).PutBasketItemAsyncAsync(basketitemGuid, basketItemChangeModel, userGuid, basketGuid), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Changes the content of basket item.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='basketitemGuid'>
            /// The basketitem unique identifier.
            /// </param>
            /// <param name='basketItemChangeModel'>
            /// The basket item change model.
            /// </param>
            /// <param name='userGuid'>
            /// </param>
            /// <param name='basketGuid'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PutBasketItemAsyncAsync(this IBasketItem operations, Guid basketitemGuid, BasketItemChangeModel basketItemChangeModel, string userGuid, string basketGuid, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.PutBasketItemAsyncWithHttpMessagesAsync(basketitemGuid, basketItemChangeModel, userGuid, basketGuid, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// Deletes the basket item.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='basketitemGuid'>
            /// The basketitem unique identifier.
            /// </param>
            /// <param name='userGuid'>
            /// </param>
            /// <param name='basketGuid'>
            /// </param>
            public static void DeleteBasketItemAsync(this IBasketItem operations, Guid basketitemGuid, string userGuid, string basketGuid)
            {
                Task.Factory.StartNew(s => ((IBasketItem)s).DeleteBasketItemAsyncAsync(basketitemGuid, userGuid, basketGuid), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes the basket item.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='basketitemGuid'>
            /// The basketitem unique identifier.
            /// </param>
            /// <param name='userGuid'>
            /// </param>
            /// <param name='basketGuid'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteBasketItemAsyncAsync(this IBasketItem operations, Guid basketitemGuid, string userGuid, string basketGuid, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.DeleteBasketItemAsyncWithHttpMessagesAsync(basketitemGuid, userGuid, basketGuid, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// Deletes all basketitems in the basket.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='basketGuid'>
            /// The basket unique identifier.
            /// </param>
            /// <param name='userGuid'>
            /// </param>
            public static void DeleteBasketItemsAsync(this IBasketItem operations, Guid basketGuid, string userGuid)
            {
                Task.Factory.StartNew(s => ((IBasketItem)s).DeleteBasketItemsAsyncAsync(basketGuid, userGuid), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes all basketitems in the basket.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='basketGuid'>
            /// The basket unique identifier.
            /// </param>
            /// <param name='userGuid'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteBasketItemsAsyncAsync(this IBasketItem operations, Guid basketGuid, string userGuid, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.DeleteBasketItemsAsyncWithHttpMessagesAsync(basketGuid, userGuid, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
