// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Checkout.Com.BasketPrototype.ClientLib
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// BasketItem operations.
    /// </summary>
    public partial interface IBasketItem
    {
        /// <summary>
        /// Creates a new basket item.
        /// </summary>
        /// <param name='basketGuid'>
        /// The basket unique identifier.
        /// </param>
        /// <param name='basketItemCreateModel'>
        /// The basket item create model.
        /// </param>
        /// <param name='userGuid'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Guid?>> PostBasketItemAsyncWithHttpMessagesAsync(Guid basketGuid, BasketItemCreateModel basketItemCreateModel, string userGuid, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Changes the content of basket item.
        /// </summary>
        /// <param name='basketitemGuid'>
        /// The basketitem unique identifier.
        /// </param>
        /// <param name='basketItemChangeModel'>
        /// The basket item change model.
        /// </param>
        /// <param name='userGuid'>
        /// </param>
        /// <param name='basketGuid'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> PutBasketItemAsyncWithHttpMessagesAsync(Guid basketitemGuid, BasketItemChangeModel basketItemChangeModel, string userGuid, string basketGuid, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Deletes the basket item.
        /// </summary>
        /// <param name='basketitemGuid'>
        /// The basketitem unique identifier.
        /// </param>
        /// <param name='userGuid'>
        /// </param>
        /// <param name='basketGuid'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteBasketItemAsyncWithHttpMessagesAsync(Guid basketitemGuid, string userGuid, string basketGuid, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Deletes all basketitems in the basket.
        /// </summary>
        /// <param name='basketGuid'>
        /// The basket unique identifier.
        /// </param>
        /// <param name='userGuid'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteBasketItemsAsyncWithHttpMessagesAsync(Guid basketGuid, string userGuid, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
